#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
#
Name     : libva-utils
Version  : 2.20.0
Release  : 33
URL      : https://github.com/intel/libva-utils/archive/2.20.0/libva-utils-2.20.0.tar.gz
Source0  : https://github.com/intel/libva-utils/archive/2.20.0/libva-utils-2.20.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: libva-utils-bin = %{version}-%{release}
Requires: libva-utils-license = %{version}-%{release}
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(libva-drm)
BuildRequires : pkgconfig(libva-wayland)
BuildRequires : pkgconfig(libva-x11)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(x11)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![Stories in Ready](https://badge.waffle.io/intel/libva-utils.png?label=ready&title=Ready)](http://waffle.io/intel/libva-utils)
[![Build Status](https://travis-ci.org/intel/libva-utils.svg?branch=master)](https://travis-ci.org/intel/libva-utils)
[![Coverity Scan Build Status](https://scan.coverity.com/projects/11613/badge.svg)](https://scan.coverity.com/projects/intel-libva-utils)

%package bin
Summary: bin components for the libva-utils package.
Group: Binaries
Requires: libva-utils-license = %{version}-%{release}

%description bin
bin components for the libva-utils package.


%package license
Summary: license components for the libva-utils package.
Group: Default

%description license
license components for the libva-utils package.


%prep
%setup -q -n libva-utils-2.20.0
cd %{_builddir}/libva-utils-2.20.0
pushd ..
cp -a libva-utils-2.20.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1694704381
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%autogen --disable-static
make  %{?_smp_mflags}

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
%autogen --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1694704381
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libva-utils
cp %{_builddir}/libva-utils-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libva-utils/946e6b5d574d506ac5f84e0826d29887b3d5a2f6 || :
cp %{_builddir}/libva-utils-%{version}/test/gtest/LICENSE %{buildroot}/usr/share/package-licenses/libva-utils/5a2314153eadadc69258a9429104cd11804ea304 || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/av1encode
/V3/usr/bin/avcenc
/V3/usr/bin/avcstreamoutdemo
/V3/usr/bin/h264encode
/V3/usr/bin/hevcencode
/V3/usr/bin/jpegenc
/V3/usr/bin/loadjpeg
/V3/usr/bin/mpeg2vaenc
/V3/usr/bin/mpeg2vldemo
/V3/usr/bin/putsurface
/V3/usr/bin/putsurface_wayland
/V3/usr/bin/sfcsample
/V3/usr/bin/vacopy
/V3/usr/bin/vainfo
/V3/usr/bin/vavpp
/V3/usr/bin/vp8enc
/V3/usr/bin/vp9enc
/V3/usr/bin/vpp3dlut
/V3/usr/bin/vppblending
/V3/usr/bin/vppchromasitting
/V3/usr/bin/vppdenoise
/V3/usr/bin/vpphdr_tm
/V3/usr/bin/vppscaling_csc
/V3/usr/bin/vppscaling_n_out_usrptr
/V3/usr/bin/vppsharpness
/usr/bin/av1encode
/usr/bin/avcenc
/usr/bin/avcstreamoutdemo
/usr/bin/h264encode
/usr/bin/hevcencode
/usr/bin/jpegenc
/usr/bin/loadjpeg
/usr/bin/mpeg2vaenc
/usr/bin/mpeg2vldemo
/usr/bin/putsurface
/usr/bin/putsurface_wayland
/usr/bin/sfcsample
/usr/bin/vacopy
/usr/bin/vainfo
/usr/bin/vavpp
/usr/bin/vp8enc
/usr/bin/vp9enc
/usr/bin/vpp3dlut
/usr/bin/vppblending
/usr/bin/vppchromasitting
/usr/bin/vppdenoise
/usr/bin/vpphdr_tm
/usr/bin/vppscaling_csc
/usr/bin/vppscaling_n_out_usrptr
/usr/bin/vppsharpness

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libva-utils/5a2314153eadadc69258a9429104cd11804ea304
/usr/share/package-licenses/libva-utils/946e6b5d574d506ac5f84e0826d29887b3d5a2f6
